---
title: "Study 1 Prep"
author: ""
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    df_print: paged
    highlight: tango
    theme: united
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  github_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
options(scipen=999)
```

This script tidies and prepares the cleaned data from Study 4.

# load packages
```{r}
if(!require('pacman')) {
	install.packages('pacman')
}

pacman::p_load(tidyverse, tidyText)
```

## load data
```{r}
data_dir = "~/Library/CloudStorage/Box-Box/BB-PRIME-PhaseII_Data_854102/BB-PRIME-PhaseII_NonIDable/BBPRIME_tournament/data/"

comments = read.csv(file.path(data_dir, "prepped/wave1_relevance.csv"), stringsAsFactors = FALSE) %>%
  mutate(group = gsub("_relevance", "", group),
         group = recode(group, "social" = "other")) %>%
  rename("comment" = value,
         "article_cond" = group) %>% 
  select(-survey_name, -scale_name, -clicks, -action)

n_words = comments %>%
  group_by(article_cond, SID, item) %>%
  tidytext::unnest_tokens(word, comment) %>%
  summarize(n_words = n())

messages = read.csv(file.path(data_dir, "prepped/wave1_messages.csv"), stringsAsFactors = FALSE) %>%
  filter(grepl("relevance|control", group)) %>%
  mutate(group = gsub("_relevance", "", group),
         group = recode(group, "social" = "other"),
         topic = "climate") %>%
  rename("article_cond" = group) %>%
  select(-survey_name, -main_headline, -snippet, -clicks, -action) %>%
  left_join(., n_words) %>%
  filter(article_cond == "control" | (!article_cond == "control" & n_words > 5)) %>% #filter out word counts less of 5 or less
  rename("article_number" = item) %>%
  filter(exclude_item == 0) %>% # filter out items excluded from the intervention tournament
  spread(scale_name, value) %>%
  select(-contains("emo"), -msg_read)

data_person = read.csv(file.path(data_dir, "prepped/wave1_emotions.csv")) %>%
  bind_rows(read.csv(file.path(data_dir, "prepped/wave1_other_dvs.csv"))) %>%
  filter(grepl("relevance|control", group)) %>%
  filter(!grepl("climate_change_cause", scale_name)) %>%
  mutate(group = gsub("_relevance", "", group),
         group = recode(group, "social" = "other")) %>%
  select(-n_missing) %>%
  group_by(scale_name, item) %>%
  mutate(value = scale(value, center = TRUE, scale = TRUE))

data_petition = read.csv(file.path(data_dir, "prepped/wave1_petitions.csv")) %>%
  filter(grepl("relevance|control", group)) %>%
  filter(!grepl("petition_sign$", scale_name)) %>%
  select(-contains("petition")) %>%
  mutate(group = gsub("_relevance", "", group),
         group = recode(group, "social" = "other"),
         value = as.numeric(value)) %>%
  select(-contains("petition")) %>%
  group_by(scale_name, item) %>%
  mutate(value = ifelse(!item == "petition_link_clicks", scale(value, center = TRUE, scale = TRUE), value))

data_actions = read.csv(file.path(data_dir, "prepped/wave1_actions.csv")) %>%
  filter(!grepl("flight", scale_name)) %>%
  filter(grepl("relevance|control", group)) %>%
  select(-value_z) %>%
  mutate(group = gsub("_relevance", "", group),
         group = recode(group, "social" = "other")) %>%
  group_by(scale_name, category, item) %>%
  mutate(value = scale(value))

exploratory_dvs = data_actions %>%
  bind_rows(., data_petition) %>%
  bind_rows(., data_person) %>%
  filter(grepl("impact|petition_share|knowledge|efficacy", scale_name)) %>%
  arrange(SID) %>%
  rename("article_cond" = group) %>%
  filter(SID %in% messages$SID)
```

# write csv
```{r}
write.csv(messages, "../data/study1_data.csv", row.names = FALSE)
write.csv(exploratory_dvs, "../data/study1_exploratory_dvs.csv", row.names = FALSE)
```
